trigger:
 branches:
   include:
   - main
 paths:
   include:
   - /infrastructure/SimEnergy/*

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Validate
  jobs:
  - job: Validate
    steps:
    - task: CmdLine@2
      displayName: "Build bicep templates"
      inputs:
        script: 'az bicep build -f ./infrastructure/SimEnergy/main.bicep'
    - publish: $(System.DefaultWorkingDirectory)/infrastructure/SimEnergy
      artifact: infrastructure

- stage: DeployToSIT
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
  jobs:
  - deployment: DeploySIT
    environment: 'sit'
    variables: 
    - group: SimEnergyEnvironment-SIT
    strategy:
     runOnce:
      deploy:
        steps:
        - template: deploy-template.yml
          parameters:
            serviceConnectionName: service_connection_sit_5ms_simenergy
            resourceGroupName: sit_5ms_simenergy

- stage: DeployToProd
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
  jobs:
  - deployment: DeployProduction
    environment: 'prd'
    variables: 
    - group: SimEnergyEnvironment-PRD
    strategy:
     runOnce:
      deploy:
        steps:
        - template: deploy-template.yml
          parameters:
            serviceConnectionName: service_connection_prd_5ms_simenergy
            resourceGroupName: prd_5ms_simenergy

